### ISSUE TITLE
can your model run in realtime just using cpu?

### ISSUE THREAD

**Issue by hdmjdp** [yoyololicon/pytorch_FFTNet#1]
can your model run in realtime  using cpu?

**Comment by yoyolicoris** [comment]
No. The best I can get is 500 samples/s with a i5-7200U.
To my knowledge it seems nobody have succeed to run at real time as paper described.

**Comment by yoyolicoris** [comment]
I have updated the implementation of FFTNet in my other repo [here](https://github.com/yoyololicon/wavenet-like-vocoder). The speed is around 1500 samples/s on the same machine, still 10x slower then realtime though. 
Probably this is the limit with pure python.
